package AdvancedSE.OmniMart;


import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

//This is like schema which tells how a particular document(entry in table) will look like

//@Document annotation is used to tell framework that this will be the structure of each document
//@Data is from the lombok library which is used to have getters, setters and ToString methods for all these attributes
//@AllArgsConstructor is from lombok, used to have a constructor which will take all these attributes as parameters
//@NoArgsConstructor is from lombok again, used to have a constructor which will not take parameters
@Document(collection="userDetails")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class userDetails {
//    @Id annotation is to tell framework that this will be the unique ID to access the documents
    @Id
    private ObjectId id;
    private String email;
    private String password;

//    Constructor which only takes email and password since id will be generated by mongodb
//    In Intellij we have an option, rightclick->generate->constructor, we can select the properties using which the
//    constructor should be created. Just a shortcut instead of typing all this.
    public userDetails(String email, String password) {
        this.email = email;
        this.password = password;
    }
}
